"""create_earnings_call

Revision ID: 115dd9b350bf
Revises: 4ccb6793535e
Create Date: 2024-01-15 13:46:41.263265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115dd9b350bf'
down_revision = '4ccb6793535e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('earnings_call', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_earnings_call_meeting_date'), ['meeting_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings_call', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_earnings_call_meeting_date'))

    op.drop_table('earnings_call')
    # ### end Alembic commands ###
