"""updata auth

Revision ID: 19ea5f8757d4
Revises: 98f3f5e71a2c
Create Date: 2020-05-23 16:42:37.475439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19ea5f8757d4'
down_revision = '98f3f5e71a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticat', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticat')
    # ### end Alembic commands ###
