"""create_stock_search_counts

Revision ID: 35be0700b6d8
Revises: f7a936a30699
Create Date: 2023-09-14 17:07:24.346278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from app import db

from app.database_setup import BasicInformation, StockSearchCounts

# revision identifiers, used by Alembic.
revision = '35be0700b6d8'
down_revision = 'f7a936a30699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_search_counts',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('search_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    with op.batch_alter_table('push_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_news', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notify_announcement', sa.Boolean(), nullable=True))
        batch_op.drop_column('notify_feed')

    basic_informations = db.session.query(BasicInformation).all()

    for basic_information in basic_informations:
        stock_search_count = StockSearchCounts()
        stock_search_count.stock_id = basic_information.id
        stock_search_count.search_count = 0
        db.session.add(stock_search_count)
        db.session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_feed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_column('notify_announcement')
        batch_op.drop_column('notify_news')

    op.drop_table('stock_search_counts')
    # ### end Alembic commands ###
