"""empty message

Revision ID: 4ccb6793535e
Revises: 35be0700b6d8
Create Date: 2023-10-02 10:24:39.551988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ccb6793535e'
down_revision = '35be0700b6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_information', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_basic_information_公司簡稱'), ['公司簡稱'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_information', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_basic_information_公司簡稱'))

    # ### end Alembic commands ###
