"""add_monthly_valuation_model

Revision ID: 62be5f006ff5
Revises: 42b368d84c3d
Create Date: 2024-03-02 19:16:14.441733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62be5f006ff5'
down_revision = '42b368d84c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_valuation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'), nullable=False),
    sa.Column('本益比', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('淨值比', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('殖利率', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('均價', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('monthly_valuation', schema=None) as batch_op:
        batch_op.create_index('stock_id_year_month', ['stock_id', 'year', 'month'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monthly_valuation', schema=None) as batch_op:
        batch_op.drop_constraint('monthly_valuation_ibfk_1', type_='foreignkey')
        batch_op.drop_index('stock_id_year_month')

    op.drop_table('monthly_valuation')
    # ### end Alembic commands ###
