"""empty message

Revision ID: 66b335a3cc8b
Revises: 6f905d638666
Create Date: 2024-05-24 21:13:26.190314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b335a3cc8b'
down_revision = '6f905d638666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_income_sheet_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('本業佔比', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_income_sheet_analysis', schema=None) as batch_op:
        batch_op.drop_column('本業佔比')

    # ### end Alembic commands ###
