"""feed_add_soruce_remove_e_stock_id

Revision ID: 672469063539
Revises: 9155bc8274e7
Create Date: 2022-09-06 07:21:59.640804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '672469063539'
down_revision = '9155bc8274e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('source', sa.String(length=20), nullable=True))
    op.drop_constraint('feed_ibfk_1', 'feed', type_='foreignkey')
    op.drop_column('feed', 'stock_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('stock_id', mysql.VARCHAR(length=6), nullable=False))
    op.create_foreign_key('feed_ibfk_1', 'feed', 'basic_information', ['stock_id'], ['id'])
    op.drop_column('feed', 'source')
    # ### end Alembic commands ###
