"""add feed and feed_Tag with many to many

Revision ID: 69957aedd51e
Revises: fa57bab93ab0
Create Date: 2021-05-01 16:59:50.416207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69957aedd51e'
down_revision = 'fa57bab93ab0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_tag',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('releaseTime', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('feedType', sa.Enum('announcement', 'news'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_releaseTime'), 'feed', ['releaseTime'], unique=False)
    op.create_table('feed_feedTag',
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('feedTag', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['feedTag'], ['feed_tag.name'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('feed_id', 'feedTag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_feedTag')
    op.drop_index(op.f('ix_feed_releaseTime'), table_name='feed')
    op.drop_table('feed')
    op.drop_table('feed_tag')
    # ### end Alembic commands ###
