"""AnnouncementIncomeSheetAnalysis year and season default null

Revision ID: 6c88aae58613
Revises: 66b335a3cc8b
Create Date: 2024-08-04 18:58:02.690974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c88aae58613'
down_revision = '66b335a3cc8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_income_sheet_analysis', schema=None) as batch_op:
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('season',
               existing_type=mysql.ENUM('1', '2', '3', '4'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement_income_sheet_analysis', schema=None) as batch_op:
        batch_op.alter_column('season',
               existing_type=mysql.ENUM('1', '2', '3', '4'),
               nullable=False)
        batch_op.alter_column('year',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
