"""earngins_call_add_file_name_and_meeting_end_date

Revision ID: 6f905d638666
Revises: 71d7ffdcc470
Create Date: 2024-04-26 13:46:46.579649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f905d638666'
down_revision = '71d7ffdcc470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings_call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('file_name_chinese', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('earnings_call', schema=None) as batch_op:
        batch_op.drop_column('file_name_chinese')
        batch_op.drop_column('meeting_end_date')

    # ### end Alembic commands ###
