"""add_notify_earnings_call_to_push_notification

Revision ID: 71d7ffdcc470
Revises: f6cbd5b63053
Create Date: 2024-04-23 11:04:57.814775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d7ffdcc470'
down_revision = 'f6cbd5b63053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_earnings_call', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('push_notification', schema=None) as batch_op:
        batch_op.drop_column('notify_earnings_call')

    # ### end Alembic commands ###
