"""empty message

Revision ID: 7b9b29865125
Revises: e9a99e6563ae
Create Date: 2020-05-25 16:28:10.592948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b9b29865125'
down_revision = 'e9a99e6563ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('authenticate', sa.Boolean(), nullable=False))
    op.drop_column('user', 'is_authenticate')
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('is_authenticate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'authenticate')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
