"""add earnings_call_summary table

Revision ID: 7d8b71bf0179
Revises: c3d4e5f6a7b8
Create Date: 2026-01-30 08:10:49.996135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8b71bf0179'
down_revision = 'c3d4e5f6a7b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earnings_call_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('earnings_call_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('capex', sa.Text(), nullable=True),
    sa.Column('capex_industry', sa.Text(), nullable=True),
    sa.Column('outlook', sa.Text(), nullable=True),
    sa.Column('concerns_and_risks', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('source_feed_ids', sa.JSON(), nullable=True),
    sa.Column('raw_ai_response', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processing', 'completed', 'failed', name='processing_status_enum'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('cost_twd', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['earnings_call_id'], ['earnings_call.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('earnings_call_id')
    )
    with op.batch_alter_table('feed_feedTag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('feed_feedTag_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('feed_feedTag_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'feed', ['feed_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'feed_tag', ['feedTag'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed_feedTag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('feed_feedTag_ibfk_2'), 'feed', ['feed_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('feed_feedTag_ibfk_1'), 'feed_tag', ['feedTag'], ['id'])

    op.drop_table('earnings_call_summary')
    # ### end Alembic commands ###
