"""add stock_id to feed

Revision ID: 8ab2c2675523
Revises: 6c88aae58613
Create Date: 2025-05-25 03:05:54.891368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ab2c2675523'
down_revision = '6c88aae58613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_information', schema=None) as batch_op:
        batch_op.alter_column('exchange_type',
               existing_type=mysql.ENUM('sii', 'otc', 'rotc', 'pub', 'delist'),
               nullable=True)

    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_id', sa.String(length=6), nullable=True))
        batch_op.create_foreign_key(None, 'basic_information', ['stock_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feed', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stock_id')

    with op.batch_alter_table('basic_information', schema=None) as batch_op:
        batch_op.alter_column('exchange_type',
               existing_type=mysql.ENUM('sii', 'otc', 'rotc', 'pub', 'delist'),
               nullable=False)

    # ### end Alembic commands ###
