"""create_data_update_date

Revision ID: 8cc39af7b97f
Revises: 756006c8e016
Create Date: 2023-06-22 17:12:23.411118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cc39af7b97f'
down_revision = '756006c8e016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('push_notification',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notify_enabled', sa.Boolean(), nullable=True),
    sa.Column('line_notify_token', sa.String(length=64), nullable=True),
    sa.Column('notify_time', sa.Time(), nullable=True),
    sa.Column('notify_feed', sa.Boolean(), nullable=True),
    sa.Column('notify_month_revenue', sa.Boolean(), nullable=True),
    sa.Column('notify_income_sheet', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('daily_information', schema=None) as batch_op:
        batch_op.alter_column('本益比',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('income_sheet', schema=None) as batch_op:
        batch_op.alter_column('營業毛利率',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('推銷費用率',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('管理費用率',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('研究發展費用率',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('營業費用率',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('營業利益率',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('稅前淨利率',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('所得稅費用率',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)
        batch_op.alter_column('本期淨利率',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=13, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income_sheet', schema=None) as batch_op:
        batch_op.alter_column('本期淨利率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('所得稅費用率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('稅前淨利率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=20, scale=2),
               existing_nullable=True)
        batch_op.alter_column('營業利益率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('營業費用率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('研究發展費用率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('管理費用率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('推銷費用率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('營業毛利率',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('daily_information', schema=None) as batch_op:
        batch_op.alter_column('本益比',
               existing_type=sa.Numeric(precision=13, scale=2),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=True)

    op.drop_table('push_notification')
    # ### end Alembic commands ###
