"""basic_information_and_feed

Revision ID: 9155bc8274e7
Revises: 99e195611707
Create Date: 2022-08-31 21:44:54.451891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9155bc8274e7'
down_revision = '99e195611707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basicInformation_feed',
    sa.Column('basic_information_id', sa.String(length=6), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basic_information_id'], ['basic_information.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], ),
    sa.PrimaryKeyConstraint('basic_information_id', 'feed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basicInformation_feed')
    # ### end Alembic commands ###
