"""initial migrate

Revision ID: 98f3f5e71a2c
Revises: 
Create Date: 2020-05-18 22:21:41.501189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '98f3f5e71a2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('profile_pic', sa.String(length=128), nullable=True),
    sa.Column('external_type', sa.String(length=16), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.alter_column('basic_information', 'exchangeType',
               existing_type=mysql.ENUM('sii', 'otc', 'rotc', 'pub', 'delist'),
               nullable=False)
    op.add_column('cashflow', sa.Column('停業單位稅前淨利淨損', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('償還公司債', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('利息收入', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('利息費用', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('取得處分不動產廠房及設備', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('取得處分無形資產', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('庫藏股現金增減', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('投資活動之淨現金流入流出', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('期初現金及約當現金餘額', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('期末現金及約當現金餘額', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('本期現金及約當現金增加減少數', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('本期稅前淨利淨損', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('營業活動之淨現金流入流出', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('現金增資', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('現金減資', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('發放現金股利', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('發行公司債', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('籌資活動之淨現金流入流出', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('繼續營業單位稅前淨利淨損', sa.BigInteger(), nullable=True))
    op.add_column('cashflow', sa.Column('退還支付所得稅', sa.BigInteger(), nullable=True))
    op.drop_column('cashflow', '取得不動產及設備')
    op.drop_column('cashflow', '取得無形資產')
    op.drop_column('cashflow', '籌資活動之淨現金流入')
    op.drop_column('cashflow', '資本支出')
    op.drop_column('cashflow', '處分投資性不動產')
    op.drop_column('cashflow', '處分不動產及設備')
    op.drop_column('cashflow', '投資性不動產公允價值調整損失')
    op.drop_column('cashflow', '營業活動之淨現金流入')
    op.drop_column('cashflow', '處分投資性不動產損失')
    op.drop_column('cashflow', '處分無形資產損失')
    op.drop_column('cashflow', '處分及報廢不動產廠房及設備損失')
    op.drop_column('cashflow', '不動產廠房及設備轉列費用數')
    op.drop_column('cashflow', '無形資產金流')
    op.drop_column('cashflow', '投資活動之淨現金流入')
    op.drop_column('cashflow', '取得投資性不動產')
    op.drop_column('cashflow', '取得不動產廠房及設備')
    op.drop_column('cashflow', '處分無形資產')
    op.drop_column('cashflow', '處分不動產廠房及設備')
    op.drop_column('cashflow', '本期現金及約當現金增加數')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashflow', sa.Column('本期現金及約當現金增加數', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.add_column('cashflow', sa.Column('處分不動產廠房及設備', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('處分無形資產', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('取得不動產廠房及設備', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('取得投資性不動產', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('投資活動之淨現金流入', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.add_column('cashflow', sa.Column('無形資產金流', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('不動產廠房及設備轉列費用數', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('處分及報廢不動產廠房及設備損失', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('處分無形資產損失', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('處分投資性不動產損失', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('營業活動之淨現金流入', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.add_column('cashflow', sa.Column('投資性不動產公允價值調整損失', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('處分不動產及設備', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('處分投資性不動產', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('資本支出', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('籌資活動之淨現金流入', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False))
    op.add_column('cashflow', sa.Column('取得無形資產', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.add_column('cashflow', sa.Column('取得不動產及設備', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_column('cashflow', '退還支付所得稅')
    op.drop_column('cashflow', '繼續營業單位稅前淨利淨損')
    op.drop_column('cashflow', '籌資活動之淨現金流入流出')
    op.drop_column('cashflow', '發行公司債')
    op.drop_column('cashflow', '發放現金股利')
    op.drop_column('cashflow', '現金減資')
    op.drop_column('cashflow', '現金增資')
    op.drop_column('cashflow', '營業活動之淨現金流入流出')
    op.drop_column('cashflow', '本期稅前淨利淨損')
    op.drop_column('cashflow', '本期現金及約當現金增加減少數')
    op.drop_column('cashflow', '期末現金及約當現金餘額')
    op.drop_column('cashflow', '期初現金及約當現金餘額')
    op.drop_column('cashflow', '投資活動之淨現金流入流出')
    op.drop_column('cashflow', '庫藏股現金增減')
    op.drop_column('cashflow', '取得處分無形資產')
    op.drop_column('cashflow', '取得處分不動產廠房及設備')
    op.drop_column('cashflow', '利息費用')
    op.drop_column('cashflow', '利息收入')
    op.drop_column('cashflow', '償還公司債')
    op.drop_column('cashflow', '停業單位稅前淨利淨損')
    op.alter_column('basic_information', 'exchangeType',
               existing_type=mysql.ENUM('sii', 'otc', 'rotc', 'pub', 'delist'),
               nullable=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
