"""add_column_to_daily_information

Revision ID: 99e195611707
Revises: 564580ff7999
Create Date: 2022-08-31 16:20:50.368475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e195611707'
down_revision = '564580ff7999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_information', sa.Column('殖利率', sa.Float(), nullable=True))
    op.add_column('daily_information', sa.Column('股價淨值比', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('daily_information', '股價淨值比')
    op.drop_column('daily_information', '殖利率')
    # ### end Alembic commands ###
