"""create recommended_stocks

Revision ID: affcb2eb9acc
Revises: 3ac4476c793d
Create Date: 2025-10-05 15:40:07.926914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affcb2eb9acc'
down_revision = '3ac4476c793d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommended_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=True),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('filter_model', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'update_date', 'filter_model', name='uix_stock_update_filter')
    )
    with op.batch_alter_table('recommended_stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommended_stocks_filter_model'), ['filter_model'], unique=False)
        batch_op.create_index(batch_op.f('ix_recommended_stocks_update_date'), ['update_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommended_stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommended_stocks_update_date'))
        batch_op.drop_index(batch_op.f('ix_recommended_stocks_filter_model'))

    op.drop_table('recommended_stocks')
    # ### end Alembic commands ###
