"""create_data_update_date

Revision ID: b774353eb528
Revises: 756006c8e016
Create Date: 2023-06-22 15:35:31.600303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b774353eb528'
down_revision = '8cc39af7b97f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_update_date',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('month_revenue_last_update', sa.Date(), nullable=True),
    sa.Column('feed_last_update', sa.Date(), nullable=True),
    sa.Column('income_sheet_last_update', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_update_date')
    # ### end Alembic commands ###
