"""updata auth

Revision ID: e9a99e6563ae
Revises: 0aa372230b4c
Create Date: 2020-05-23 18:39:29.741282

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e9a99e6563ae'
down_revision = '0aa372230b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_authenticate', sa.Boolean(), nullable=False))
    op.drop_column('user', 'authenticate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authenticate', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'is_authenticate')
    # ### end Alembic commands ###
