"""alter feed_last_update to news and announcement update

Revision ID: f7a936a30699
Revises: 910087ac2aa3
Create Date: 2023-08-28 10:58:25.449602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7a936a30699'
down_revision = '910087ac2aa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_update_date', schema=None) as batch_op:
        batch_op.alter_column(column_name='feed_last_update', new_column_name='announcement_last_update', type_=sa.Date())
        batch_op.add_column(sa.Column('news_last_update', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_update_date', schema=None) as batch_op:
        batch_op.alter_column(column_name='announcement_last_update', new_column_name='feed_last_update', type_=sa.Date())
        batch_op.drop_column('news_last_update')

    # ### end Alembic commands ###
