"""migrate init

Revision ID: fa57bab93ab0
Revises: 
Create Date: 2020-09-25 19:32:12.454304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa57bab93ab0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basic_information',
    sa.Column('id', sa.String(length=6), autoincrement=False, nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('exchangeType', sa.Enum('sii', 'otc', 'rotc', 'pub', 'delist'), nullable=False),
    sa.Column('公司名稱', sa.Text(), nullable=False),
    sa.Column('公司簡稱', sa.String(length=10), nullable=True),
    sa.Column('產業類別', sa.String(length=10), nullable=True),
    sa.Column('外國企業註冊地國', sa.String(length=10), nullable=True),
    sa.Column('住址', sa.Text(), nullable=True),
    sa.Column('營利事業統一編號', sa.String(length=8), nullable=True),
    sa.Column('董事長', sa.String(length=50), nullable=True),
    sa.Column('總經理', sa.String(length=50), nullable=True),
    sa.Column('發言人', sa.String(length=50), nullable=True),
    sa.Column('發言人職稱', sa.String(length=20), nullable=True),
    sa.Column('代理發言人', sa.String(length=50), nullable=True),
    sa.Column('總機電話', sa.String(length=30), nullable=True),
    sa.Column('成立日期', sa.String(length=10), nullable=True),
    sa.Column('上市上櫃興櫃公開發行日期', sa.String(length=10), nullable=True),
    sa.Column('普通股每股面額', sa.String(length=15), nullable=True),
    sa.Column('實收資本額', sa.BigInteger(), nullable=True),
    sa.Column('已發行普通股數或TDR原發行股數', sa.BigInteger(), nullable=True),
    sa.Column('私募普通股', sa.BigInteger(), nullable=True),
    sa.Column('特別股', sa.BigInteger(), nullable=True),
    sa.Column('編製財務報告類型', sa.String(length=2), nullable=True),
    sa.Column('普通股盈餘分派或虧損撥補頻率', sa.String(length=6), nullable=True),
    sa.Column('普通股年度現金股息及紅利決議層級', sa.String(length=3), nullable=True),
    sa.Column('股票過戶機構', sa.Text(), nullable=True),
    sa.Column('過戶電話', sa.String(length=30), nullable=True),
    sa.Column('過戶地址', sa.Text(), nullable=True),
    sa.Column('簽證會計師事務所', sa.Text(), nullable=True),
    sa.Column('簽證會計師一', sa.String(length=20), nullable=True),
    sa.Column('簽證會計師二', sa.String(length=20), nullable=True),
    sa.Column('英文簡稱', sa.Text(), nullable=True),
    sa.Column('英文通訊地址', sa.Text(), nullable=True),
    sa.Column('傳真機號碼', sa.String(length=30), nullable=True),
    sa.Column('電子郵件信箱', sa.Text(), nullable=True),
    sa.Column('公司網址', sa.Text(), nullable=True),
    sa.Column('投資人關係聯絡人', sa.String(length=50), nullable=True),
    sa.Column('投資人關係聯絡人職稱', sa.String(length=30), nullable=True),
    sa.Column('投資人關係聯絡電話', sa.String(length=30), nullable=True),
    sa.Column('投資人關係聯絡電子郵件', sa.Text(), nullable=True),
    sa.Column('公司網站內利害關係人專區網址', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('profile_pic', sa.String(length=128), nullable=True),
    sa.Column('external_type', sa.String(length=16), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('authenticate', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('balance_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.Enum('1', '2', '3', '4'), nullable=False),
    sa.Column('現金及約當現金', sa.BigInteger(), nullable=True),
    sa.Column('透過其他綜合損益按公允價值衡量之金融資產流動', sa.BigInteger(), nullable=True),
    sa.Column('透過損益按公允價值衡量之金融資產流動', sa.BigInteger(), nullable=True),
    sa.Column('按攤銷後成本衡量之金融資產流動', sa.BigInteger(), nullable=True),
    sa.Column('存貨', sa.BigInteger(), nullable=True),
    sa.Column('應收帳款淨額', sa.BigInteger(), nullable=True),
    sa.Column('應收票據淨額', sa.BigInteger(), nullable=True),
    sa.Column('流動資產合計', sa.BigInteger(), nullable=True),
    sa.Column('透過其他綜合損益按公允價值衡量之金融資產非流動', sa.BigInteger(), nullable=True),
    sa.Column('透過損益按公允價值衡量之金融資產非流動', sa.BigInteger(), nullable=True),
    sa.Column('按攤銷後成本衡量之金融資產非流動', sa.BigInteger(), nullable=True),
    sa.Column('採用權益法之投資', sa.BigInteger(), nullable=True),
    sa.Column('不動產廠房及設備', sa.BigInteger(), nullable=True),
    sa.Column('無形資產', sa.BigInteger(), nullable=True),
    sa.Column('非流動資產合計', sa.BigInteger(), nullable=True),
    sa.Column('資產總計', sa.BigInteger(), nullable=True),
    sa.Column('短期借款', sa.BigInteger(), nullable=True),
    sa.Column('一年或一營業週期內到期長期負債', sa.BigInteger(), nullable=True),
    sa.Column('應付帳款', sa.BigInteger(), nullable=True),
    sa.Column('應付票據', sa.BigInteger(), nullable=True),
    sa.Column('流動負債合計', sa.BigInteger(), nullable=True),
    sa.Column('長期借款', sa.BigInteger(), nullable=True),
    sa.Column('應付公司債', sa.BigInteger(), nullable=True),
    sa.Column('非流動負債合計', sa.BigInteger(), nullable=True),
    sa.Column('負債總計', sa.BigInteger(), nullable=True),
    sa.Column('股本合計', sa.BigInteger(), nullable=True),
    sa.Column('資本公積合計', sa.BigInteger(), nullable=True),
    sa.Column('保留盈餘合計', sa.BigInteger(), nullable=True),
    sa.Column('非控制權益', sa.BigInteger(), nullable=True),
    sa.Column('歸屬於母公司業主之權益', sa.BigInteger(), nullable=True),
    sa.Column('權益總計', sa.BigInteger(), nullable=True),
    sa.Column('負債及權益總計', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cashflow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.Enum('1', '2', '3', '4'), nullable=False),
    sa.Column('停業單位稅前淨利淨損', sa.BigInteger(), nullable=True),
    sa.Column('繼續營業單位稅前淨利淨損', sa.BigInteger(), nullable=True),
    sa.Column('本期稅前淨利淨損', sa.BigInteger(), nullable=True),
    sa.Column('折舊費用', sa.BigInteger(), nullable=True),
    sa.Column('攤銷費用', sa.BigInteger(), nullable=True),
    sa.Column('利息收入', sa.BigInteger(), nullable=True),
    sa.Column('利息費用', sa.BigInteger(), nullable=True),
    sa.Column('退還支付所得稅', sa.BigInteger(), nullable=True),
    sa.Column('營業活動之淨現金流入流出', sa.BigInteger(), nullable=True),
    sa.Column('取得處分不動產廠房及設備', sa.BigInteger(), nullable=True),
    sa.Column('取得處分無形資產', sa.BigInteger(), nullable=True),
    sa.Column('投資活動之淨現金流入流出', sa.BigInteger(), nullable=True),
    sa.Column('現金增資', sa.BigInteger(), nullable=True),
    sa.Column('現金減資', sa.BigInteger(), nullable=True),
    sa.Column('庫藏股現金增減', sa.BigInteger(), nullable=True),
    sa.Column('發放現金股利', sa.BigInteger(), nullable=True),
    sa.Column('償還公司債', sa.BigInteger(), nullable=True),
    sa.Column('發行公司債', sa.BigInteger(), nullable=True),
    sa.Column('籌資活動之淨現金流入流出', sa.BigInteger(), nullable=True),
    sa.Column('期初現金及約當現金餘額', sa.BigInteger(), nullable=True),
    sa.Column('期末現金及約當現金餘額', sa.BigInteger(), nullable=True),
    sa.Column('本期現金及約當現金增加減少數', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_information',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('本日收盤價', sa.Float(), nullable=True),
    sa.Column('本日漲跌', sa.Float(), nullable=True),
    sa.Column('近四季每股盈餘', sa.Float(), nullable=True),
    sa.Column('本益比', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    op.create_table('income_sheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.Enum('1', '2', '3', '4'), nullable=False),
    sa.Column('營業收入合計', sa.BigInteger(), nullable=True),
    sa.Column('營業成本合計', sa.BigInteger(), nullable=True),
    sa.Column('營業毛利', sa.BigInteger(), nullable=True),
    sa.Column('營業毛利率', sa.Float(), nullable=True),
    sa.Column('推銷費用', sa.BigInteger(), nullable=True),
    sa.Column('推銷費用率', sa.Float(), nullable=True),
    sa.Column('管理費用', sa.BigInteger(), nullable=True),
    sa.Column('管理費用率', sa.Float(), nullable=True),
    sa.Column('研究發展費用', sa.BigInteger(), nullable=True),
    sa.Column('研究發展費用率', sa.Float(), nullable=True),
    sa.Column('營業費用', sa.BigInteger(), nullable=True),
    sa.Column('營業費用率', sa.Float(), nullable=True),
    sa.Column('營業利益', sa.BigInteger(), nullable=True),
    sa.Column('營業利益率', sa.Float(), nullable=True),
    sa.Column('營業外收入及支出合計', sa.BigInteger(), nullable=True),
    sa.Column('稅前淨利', sa.BigInteger(), nullable=True),
    sa.Column('稅前淨利率', sa.Float(), nullable=True),
    sa.Column('所得稅費用', sa.BigInteger(), nullable=True),
    sa.Column('所得稅費用率', sa.Float(), nullable=True),
    sa.Column('本期淨利', sa.BigInteger(), nullable=True),
    sa.Column('本期淨利率', sa.Float(), nullable=True),
    sa.Column('母公司業主淨利', sa.BigInteger(), nullable=True),
    sa.Column('基本每股盈餘', sa.Float(), nullable=True),
    sa.Column('稀釋每股盈餘', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('month_revenue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Enum('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'), nullable=False),
    sa.Column('update_date', sa.Date(), nullable=False),
    sa.Column('當月營收', sa.BigInteger(), nullable=True),
    sa.Column('上月營收', sa.BigInteger(), nullable=True),
    sa.Column('去年當月營收', sa.BigInteger(), nullable=True),
    sa.Column('上月比較增減', sa.Float(), nullable=True),
    sa.Column('去年同月增減', sa.Float(), nullable=True),
    sa.Column('當月累計營收', sa.BigInteger(), nullable=True),
    sa.Column('去年累計營收', sa.BigInteger(), nullable=True),
    sa.Column('前期比較增減', sa.Float(), nullable=True),
    sa.Column('備註', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_commodity',
    sa.Column('stock_id', sa.String(length=6), nullable=False),
    sa.Column('stock_future', sa.Boolean(), nullable=False),
    sa.Column('stock_option', sa.Boolean(), nullable=False),
    sa.Column('small_stock_future', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['basic_information.id'], ),
    sa.PrimaryKeyConstraint('stock_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_commodity')
    op.drop_table('month_revenue')
    op.drop_table('income_sheet')
    op.drop_table('daily_information')
    op.drop_table('cashflow')
    op.drop_table('balance_sheet')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('basic_information')
    # ### end Alembic commands ###
